---
galaxy_info:
  author: Roman Agabekov
  description: Role for configuration php-fpm pools for Debain/Ubuntu/Centos
  company: Initlab LLC
  license: license (BSD, MIT)
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: RedHat
    versions:
    - all
  galaxy_tags:
  - development
  - web
  categories:
  - development
  - web
dependencies: []
