---
# tasks file for exim4
- name: Install Exim4 package
  apt: name=exim4 state=present
  tags: [exim]

- name: Exim4 Configuration
  template: src=update-exim4.conf.j2 dest=/etc/exim4/update-exim4.conf.conf
  tags: [exim]
  notify: update exim4.conf

- name: Create catch all configuration
  template: src=conf.d/router/01_exim4-config_catch_all dest=/etc/exim4/conf.d/router/01_exim4-config_catch_all
  when: (exim4_catch_all_email is defined) and exim4_catch_all_email
  notify: update exim4.conf

- name: Delete catch all configuration
  file: path=/etc/exim4/conf.d/router/01_exim4-config_catch_all state=absent
  when: (not exim4_catch_all_email is defined) or (not exim4_catch_all_email)
  notify: update exim4.conf

- name: Create /etc/passwd.client
  template: src=passwd.client dest=/etc/exim4/passwd.client group=Debian-exim
  notify: update exim4.conf

- name: Configure ACLs and main configuration
  template: src="conf.d/{{ item }}" dest=/etc/exim4/conf.d/{{ item }}
  with_items:
    - acl/30_exim4-config_check_rcpt
    - acl/31_exim4-config_check_not_smtp
    - main/03_exim4-config_extra_options
  notify: update exim4.conf